### ISSUE TITLE
Couldn't connect to MCP server obsidian-brain

### ISSUE THREAD

**Issue by quentinzhang** [Shubhaankar-Sharma/obsidian-brain#2]
I try to use it locally but always get "Couldn't connect to MCP server obsidian-brain".

Can you make it more clear about how to run the server and connect with Claude app? thanks!

**Comment by Shubhaankar-Sharma** [comment]
@quentinzhang thanks for reporting, will make it clearer in the readme, to help me debug why its not working for you - 1) can you post the config you're using for the obsidian mcp server? 2) can you maybe run `tail -n 20 -f ~/Library/Logs/Claude/mcp*.log` and restart claude - this should throw the error thats happening

**Comment by Shubhaankar-Sharma** [comment]
@quentinzhang Hey! i've fixed the issue https://github.com/Shubhaankar-Sharma/obsidian-brain/blob/master/README.md#published-servers-configuration check out the new config - specifically add a @0.1.3 to run the new version via claude, it should work now 😄

**Comment by quentinzhang** [comment]
@Shubhaankar-Sharma I have pulled the update but so far the issue is not fixed at my side. I am using Development/Unpublished Servers Configuration, and the following is my config:

{
......
    "obsidian-brain": {
      "command": "uvx",
      "args": [
        "--directory",
        "/var/gpt/obsidian-brain",
        "run",
        "obsidian-brain"
      ],
      "env": {
        "OBSIDIAN_MIND_PATH": "/Users/everfly/Library/Mobile Documents/iCloud~md~obsidian/Documents/second brain"
      }
    },
.......
}

/var/gpt/obsidian-brain is my local path of this repo.

When I run tail -n 20 -f ~/Library/Logs/Claude/mcp*.log, the following is the output:

2024-12-02T02:23:06.441Z [error] Could not start MCP server obsidian-brain: Error: spawn uvx ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn uvx',
  path: 'uvx',
  spawnargs: [Array]
}

Do I need to run any command to start the server before using it? Thanks for the help!

**Comment by Shubhaankar-Sharma** [comment]
@quentinzhang Hey, so in the dev config its "uv" not "uvx" - uvx is for tools/packages... so just replace the "command": "uvx" with "uv" and it should run... and i'm assuming /var/gpt/obsidian-brain is where the code is ? 😄

**Comment by quentinzhang** [comment]
I made the change and Claude still can't connect to the mcp server, but actually I can use inspector to connect successfully now. It made me crazy 😫

**Comment by quentinzhang** [comment]
@Shubhaankar-Sharma finally found the reason. It is because Claude app can't found uvx command unless I put the full path of uvx command into the server config. It works now, great job!

**Comment by Shubhaankar-Sharma** [comment]
ahhhhhh F, awesome @quentinzhang , well thanks for opening the issue, helped me find a bug still lol :p
